# Configuration of where to symlink the various dotfiles.
# Paths are relative to the dotfiles folder.

- from: ~/.bashrc
  to: bashrc
- from: ~/.bashrc.d
  to: bashrc.d
- from: ~/.bash_profile
  to: bash_profile

- from: ~/.gitconfig
  to: gitconfig
- from: ~/.gitignore
  to: gitignore

- from: ~/.pythonrc.py
  to: pythonrc.py

- from: ~/.vimperatorrc
  to: vimperatorrc

- from: ~/.irssi
  to: irssi

- from: ~/.ghci
  to: ghci
